name: Build Jar File

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-jar:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository auschecken
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Java einrichten
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Ersetze durch deine benötigte Java-Version
          distribution: 'temurin'

      # 3. Jar-Datei erstellen
      - name: Build Jar File
        run: ./gradlew build

      # 4. Artefakt hochladen (optional)
      - name: Upload Jar Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jar-file
          path: build/libs/*.jar
