name: Test Coverage and Upload

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-upload-coverage:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository auschecken
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Java einrichten
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Passe die Java-Version an, falls nötig
          distribution: 'temurin'

      # 3. Gradle-Build und Tests ausführen
      - name: Run Tests with Coverage
        run: ./gradlew clean test jacocoTestReport

      # 4. Testabdeckungsbericht hochladen
      - name: Upload Test Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage-report
          path: build/reports/jacoco/test/html/**
